clang \
--target=wasm32-unknown-wasi \
--sysroot .lib/wasi-libc \
-nostartfiles \
-Wl,--import-memory \
-Wl,--no-entry \
-I .lib/gmp/include \
-I .submodules/secp256k1/include \
-I .submodules/secp256k1 \
-D HAVE_CONFIG_H=true \
-Wl,--export="get_publickey" \
-o wasm/get_publickey.wasm  src/get_publickey.c .submodules/secp256k1/src/secp256k1.c